### PR TITLE
Update PH7Tpl.class.php

### PR DESCRIPTION
**Pull request by Undefined-Variables**
Minor changes in the comments. Ideally you should have these set to "1" which is equal to "TRUE", unless you like getting hacked?

### CODE REVIEW

**Comment by polynamaude** [comment]
@Undefined-Variables I don't know where you get your things because sometime you seem one of the only one seeing them.
https://www.php.net/manual/en/language.types.boolean.php

Could you please show where do you get an error ?
Thanks

**Comment by Undefined-Variables** [comment]
Hey @polynamaude nice to see you :) Yeah sure no problem I took a couple of screenshots and yes I odiously know how PHP works, just not in this case? Sorry about the black outs.

Capture1

Capture2

**Comment by Undefined-Variables** [comment]
@polynamaude I am only sharing the important things that I come across. I thought the idea is to all share what we learn and we can make the software better and more secure. If you would prefer me not to then you only have to say so... Its added work for me and was helping for the right reasons? Your call mate?

**Comment by polynamaude** [comment]
@Undefined-Variables I'm just trying to figure out why you seem to have problems that others don't (starting with me).
Also, you kind of burned your chances somewhat with some actions in the past by being to quick on making links so I just want to make sure, that's all.

**Comment by Undefined-Variables** [comment]
@polynamaude I totally understand where you are coming from and I have no excuse for the past but I have been though a lot since then and had a really bad time lately but the one thing that has kept me grounded is this software. I have spent so many hours working on this and have learned so much from it that I just want to give something back to it. We learn and mature in life. Many people would have changed username but not me. 

As for why I find problems... I am not asking for help with anything and could solve my own issues and keep the knowledge to myself, I expect many people have this view but I think the software should be available to everyone in the best possible way, It would be wrong to keep these things secret on an open source project. 

Also many users have problems look at the issues board! Many don’t have a clue where to start, that’s why I try and offer advice when I know how to solve the problem. 

I had to install a fresh copy and do all the customisations again because I need a dev server to try some more adventures things on! The sort of things that easily break a working live website so decided to share what I have learned with you! 

I know I can’t in do things but I can make the things I do from now better!  I will continue to help others and submit pull requests until I’m asked not to! You only need say it once and I will not come back! I love this software and PHP and programming in general and I’m going to do as much as I can in the time I have left...

**Pull request closed without merging**
