### PR TITLE
Suggestion 

### PR DESCRIPTION
**Pull request by Undefined-Variables**

### CODE REVIEW

**Comment by Undefined-Variables** [comment]
Stop neg values

**Comment by Undefined-Variables** [comment]
Sorry forget this I was looking at it wrong... 

Can you spare a minute please  to explain how the paypal call back works.

I have created a gift system, users buy credits and pay with paypal payment, credits are then credited to members table in a new column called credits, then users are able to spend the credits on gifts and send them to each other... 

I've added management panels for adding gifts and packages of 1, 3,5,9 gifts etc. It works like a dream the users balance that is stored in DB  is displayed as I intended, the payment gets passed to paypal just as it should with correct amount, name, ect but when you pay and get redirected back to the site the banner says success credits have been added to your account but I don't know how to catch the call back from paypal to confirm payment has been made??? I have to manually add the value. 

Everytime I test it costs me £1 and paypal steel 0.30p each time and place money on hold  🤷‍♂️ Don't like paypal at all.

So what value is returned? Custom??? base64decode 

````

  ->param('notify_url', Uri::get('gifts', 'main', 'notification', 'PH7\PayPal,' . $oGifts->groupId))

````

**Comment by Undefined-Variables** [comment]
Look at this its daylight robbery... How can they get away with charging 33% fee?

**Comment by pH-7** [comment]
> Look at this its daylight robbery... How can they get away with charging 33% fee? And then they hold it for weeks too.
> 
> 

In the UK, PayPal takes 2.90% per transaction, plus a fixed fee of 0.30GBP for every transaction made. Source: https://www.paypal.com/uk/webapps/mpp/merchant-fees

They don't charge you 33% (that would be absurd indeed), but indeed, for small payments like 1GBP, it sounds a lot! I agree with you. However, for bigger transactions, the fee is much more acceptable, although it isn't the cheapest, but one of the most popular services.

**Comment by pH-7** [comment]
> @pH-7 Sorry forget this I was looking at it wrong...
> 
> Can you spare a minute please to explain how the paypal call back works.
> 
 
>   ->param('notify_url', Uri::get('gifts', 'main', 'notification', 'PH7\PayPal,' . $oGifts->groupId))
> ```

Sure! So, `notify_url` is a hidden field that PayPal triggers when the payment is completed.

The value of that field points to the "notification" action. For instance, in the payment module, it will call the following method https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/53e7ab37fb92bae094ab66e0c6c2b0a1f927d516/_protected/app/system/modules/payment/controllers/MainController.php#L178-L193

And the following argument `PH7\PayPal,' . $oMembership->groupId` specified in `Uri::get()` is used in https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/53e7ab37fb92bae094ab66e0c6c2b0a1f927d516/_protected/app/system/modules/payment/controllers/MainController.php#L178  arguments, `$sGatewayName = '', $iItemNumber = 0`, to let the method knows what payment gateway it is, and what item.
https://developer.paypal.com/docs/api-basics/notifications/ipn/IPNSetup/#setting-up-ipn-notifications-on-paypal

**Comment by pH-7** [comment]
>
> So what value is returned? Custom??? base64decode
>


The "custom" field holds useful information.  Like the `notify_url`, it is also used by PayPal. PayPal will send it back to the website once the payment has been made. It is used for sending unique customer ID's, inventery or member ID's, etc. More information concerning that field can be found on the page https://www.paypal.com/uk/smarthelp/article/how-do-i-add-paypal-checkout-to-my-custom-shopping-cart-ts1200

In the purpose of the payment module, it holds the membership ID (the ID of the membership the user is buying) and the membership price, delimited with a `|` (because here, we want to store more than one value in a field).

Then, when PayPal redirects the user to the process page of our website, it reads those information here https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/10cbc8ececd8b6404c0c8479fe709ef81663742d/_protected/app/system/modules/payment/controllers/MainController.php#L288 (which are sent back by PayPal).

Finally, the `custom` field is encoded in base64 to prevent users to read easily the value of that hidden field from their browser's source code console. It's just an additional precaution.

**Comment by pH-7** [comment]
Hope it helps 😊

Let me know if you wanted to know something else.


Have a great weekend! Good luck! I know, sometimes it's like a maze to understand it 😁

**Comment by Undefined-Variables** [comment]
@pH-7 Yeah I worked it out myself, you use the pipe | to seperate the values then explode it and the info is accessed with array keys. I had to have 4 fields so becomes [0] [1] [2] [3]. 

I have the users side complete, it shows the gifts that will be added/removed via the admin panel. All I have left to do is the uploading/management forms on the admin side :)  few pictures as they say a million words...

**Comment by Undefined-Variables** [comment]
Looking okay isn't it. It works lovely too :) Thanks for the reply, it took me 2 days to work this out but as soon as I understood the pipe and the array being exploded it all snapped together in my head.

**Comment by polynamaude** [comment]
@Undefined-Variables You can get info about the paypal SDK and API on the paypal website.
https://developer.paypal.com/docs/

**Comment by polynamaude** [comment]
@Undefined-Variables Love the "orgasm".

**Comment by Undefined-Variables** [comment]
Hey @pH-7 I'm having a problem with form tokens and was hoping you might know something that may help.

The form works on the first attempt but if you use it again without clearing your cache and history all you get is a blank page. If I remove the token from the form you get the same result but on the first try. 

The form clears the cache before redirecting you but is odvously not refreshing the token on the next use of the form. 

Is there a way to clear the token and issue a new one and ensure its valid? I have this happen in mail compose form sometimes and the only way I can get it going again is to delete all read messages in the database. 

It's an odd problem and I really don't know what to do next as it's written in exactly the same way as other working forms... Any advice would be wonderful 😊

**Comment by Undefined-Variables** [comment]
Don't worry I solved it. Not sure why messaging one happens yet but I will get to the bottom of it :)

**Comment by pH-7** [comment]
> Looking okay isn't it. It works lovely too :) Thanks for the reply, it took me 2 days to work this out but as soon as I understood the pipe and the array being exploded it all snapped together in my head.

Well done!! You can be proud of you 🏆

**Comment by pH-7** [comment]
> Hey @pH-7 I'm having a problem with form tokens and was hoping you might know something that may help.
> 
> The form works on the first attempt but if you use it again without clearing your cache and history all you get is a blank page. If I remove the token from the form you get the same result but on the first try.
> 
> The form clears the cache before redirecting you but is odvously not refreshing the token on the next use of the form.
> 
> Is there a way to clear the token and issue a new one and ensure its valid? I have this happen in mail compose form sometimes and the only way I can get it going again is to delete all read messages in the database.
> 
> It's an odd problem and I really don't know what to do next as it's written in exactly the same way as other working forms... Any advice would be wonderful 😊

Do you speak about the CSRF token?  The one added as `$oForm->addElement(new Token('form_id')` in the forms?

If so, try to disable them through your admin dashboard (Admin Panel -> Setting -> General -> Security -> "Enable/Disable CSRF security tokens in forms" and try again.

That option disables all security tokens present in the forms. You will then directly see if the problem is from there :)

**Comment by pH-7** [comment]
> Hey @pH-7 I'm having a problem with form tokens and was hoping you might know something that may help.
> 
> The form works on the first attempt but if you use it again without clearing your cache and history all you get is a blank page. If I remove the token from the form you get the same result but on the first try.
> 
> The form clears the cache before redirecting you but is odvously not refreshing the token on the next use of the form.
> 
> Is there a way to clear the token and issue a new one and ensure its valid? I have this happen in mail compose form sometimes and the only way I can get it going again is to delete all read messages in the database.
> 
> It's an odd problem and I really don't know what to do next as it's written in exactly the same way as other working forms... Any advice would be wonderful 😊

Do you speak about the CSRF token?  The one added as `$oForm->addElement(new Token('form_id')` in the forms?

If so, try to disable them through your admin dashboard (Admin Panel -> Setting -> General -> Security -> "Enable/Disable CSRF security tokens in forms" and try again.

That option disables all security tokens present in the forms. You will then directly see if the problem is from there :)

P.S. Normally, it doesn't give back a blank page. It would instead shows an error message.

Do you have any relevant logs in `_protected/data/log/pH7log/`?

**Comment by pH-7** [comment]
> Hey @pH-7 I'm having a problem with form tokens and was hoping you might know something that may help.
> 
> The form works on the first attempt but if you use it again without clearing your cache and history all you get is a blank page. If I remove the token from the form you get the same result but on the first try.
> 
> The form clears the cache before redirecting you but is odvously not refreshing the token on the next use of the form.
> 
> Is there a way to clear the token and issue a new one and ensure its valid? I have this happen in mail compose form sometimes and the only way I can get it going again is to delete all read messages in the database.
> 
> It's an odd problem and I really don't know what to do next as it's written in exactly the same way as other working forms... Any advice would be wonderful 😊

Do you speak about the CSRF token?  The one added as `$oForm->addElement(new Token('form_id')` in the forms?

If so, try to disable them through your admin dashboard (Admin Panel -> Setting -> General -> Security -> "Enable/Disable CSRF security tokens in forms" and try again.

That option disables all security tokens present in the forms. You will then directly see if the problem is from there :)

P.S. Normally, it doesn't give back a blank page. It would instead shows an error message.

Do you have any relevant logs in `_protected/data/log/pH7log/`?

**Comment by Undefined-Variables** [comment]
I have split the two halfs of the module user/admin and had a spelling mistake on one of the forms... 

I have put the gifts in to catagories :) 



Then on messages compose form I have used a jQuery plugin to put them in a cool dropdown menu...





Now all I have to do is work out a way to pass the JS select option (client side) back to PHP (server side) this may be a little harder haha...

**Comment by Undefined-Variables** [comment]
I have also updated jQuery to latest version and dont see any incompatability issues so far :)

**Comment by Undefined-Variables** [comment]
All I ever have in that log file is a single line...

    Error calling web service for banned IP URL name: https://www.badips.com/get/list/ssh/2?age=30d

**Comment by pH-7** [comment]
> I have also updated jQuery to latest version and dont see any incompatability issues so far :)

Do you mind creating a PR for it?

**Comment by pH-7** [comment]
> I have split the two halfs of the module user/admin and had a spelling mistake on one of the forms...
> 
> I have put the gifts in to catagories :)
> 
> 
> 
> Then on messages compose form I have used a jQuery plugin to put them in a cool dropdown menu...
> 
> 
> 
> 
> 
> Now all I have to do is work out a way to pass the JS select option (client side) back to PHP (server side) this may be a little harder haha...

Yes, especially when you use payment gateways, it can be very tricky.

**Comment by pH-7** [comment]
> All I ever have in that log file is a single line...
> 
> ```
> Error calling web service for banned IP URL name: https://www.badips.com/get/list/ssh/2?age=30d
> ```
> 
> Any useful error data ends up in DB table ERROR_LOGS

Might be a good news... but still, it doesn't explain why you get a blank page. Are you sure you don't have an `exit()` or `die()`  somewhere...? 

Are you sure all actions (and the notify_url page URL) have correct view output (`$this->output();`). When you forget to output the view, you would also get a blank page.

**Comment by Undefined-Variables** [comment]
@pH-7 No die or exit anywhere and yeah getting the selectedData from ddslick and getting it in to a usable form was the biggest headache I have had yet but many hours of trial and error and I have the .value and .text values in a form... Not a lot left to do now. I have to check users credit, debit the credit and add the Tx to the table I have created and if all that goes well allow the message to be sent :) 

I have a much better understanding of jQuery and JS thanks to all the above, Currently getting the annoying blank page again and there is no errors in DB or files so think its going to be a few hours debugging by eye! 

nu1

nu2

The Id field will become a hidden field once I have completed it :)

**Comment by Undefined-Variables** [comment]
@pH-7 Do you have any idea how to stop a form being resubmitted using pfbc? I have trolled the deepths of the internet and tried everything I can think of but there doesn't seem to be much documentation on pfbc. Any ideas?

**Comment by Undefined-Variables** [comment]
Just found the docs but cant see a method to stop refreshing of a form :/

**Pull request closed without merging**
