### PR TITLE
is it possible to make user top bar taller to fit a bigger logo?

### PR DESCRIPTION
**Pull request by chalit9999**
Hi i would like to make the top bar menu taller to fit a larger Logo  and larger font to navigate easier, is it possible?   Thanks

### CODE REVIEW

**Comment by polynamaude** [comment]
Hi !
I think you may have got it wrong (or maybe it's me).
Don't make a Pull Request to ask question. This is when you want to suggest modification of our code base.

For help, make a "issue".

Thanks

**Comment by chalit9999** [comment]
i got it wrong, i'm sorry, thanks for your advise

ในวันที่ พฤ. 29 พ.ย. 2018 เวลา 19:44 Polyna-Maude R.-Summerside <
notifications@github.com> เขียนว่า:

**Comment by pH-7** [comment]
Thanks for your help @polynamaude! :) Really appreciate it. 

I will close this invalid PR by now.

Cheers,
Pierre

**Comment by polynamaude** [comment]
Hi @pH-7 
He opened an issue. I answered my best but didn't had time to find the exact place for the top bar size in the templates.

**Pull request closed without merging**
