### PR TITLE
Add block countries

### PR DESCRIPTION
**Pull request by pH-7**
Allow to a whole block country easily to avoid spammers or unwanted users from countries the website don't target.

screen shot 2018-05-20 at 9 07 57 pm

screen shot 2018-05-20 at 9 33 40 pm

### CODE REVIEW

**Comment by polynamaude** [comment]
I will look how you've done this and change what I've done to have it on the same model of design.

Question, you told me to make a branch and push onto the repo I've forked or this one?

Thx

Le 20 mai 2018 15:38:55 EDT, "♚ PH⑦ Soria ♛" <notifications@github.com> a écrit :
>Allow to a whole block country easily to avoid spammers or unwanted
>users from countries the website don't target.
>
>
>screen shot 2018-05-20 at 9 07 57 pmsrc="https://user-images.githubusercontent.com/1325411/40282902-2ac0bdcc-5c76-11e8-8c39-e1633681c63c.png">
>
>screen shot 2018-05-20 at 9 33 40 pmsrc="https://user-images.githubusercontent.com/1325411/40282901-2aa853c2-5c76-11e8-8ee5-5544e4d5dee6.png">
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/206
>
>-- Commit Summary --
>
>  * Change comment to better one
>  * Make comments shorter; More readable
>  * Add block countries tables to SQL files
>  * Add BlockCountry Model
>  * Add migration script for BlockCountry SQL queries
>  * Add Block Country page
>  * Integrate Block Country (if any are found) to the Core Controller
>  * Add BlockCountry link on admin Tool drop-down menu
>  * Add PFBC BlockCountry form (and process form)
>
>-- File Changes --
>
>    M _install/data/sql/MySQL/pH7_Core.sql (10)
>    M _install/data/sql/PostgreSQL/pH7_Core.sql (14)
>    M _protected/app/configs/bans/bank_account.txt (3)
>    M _protected/app/configs/bans/email.txt (4)
>    M _protected/app/configs/bans/ip.txt (4)
>    M _protected/app/configs/bans/username.txt (2)
>    M _protected/app/configs/bans/word.txt (2)
>    M _protected/app/includes/classes/DbTableName.php (1)
>M _protected/app/system/modules/admin123/controllers/ToolController.php
>(8)
>A _protected/app/system/modules/admin123/forms/BlockCountryForm.php
>(49)
>A
>_protected/app/system/modules/admin123/forms/processing/BlockCountryFormProcess.php
>(42)
>A
>_protected/app/system/modules/admin123/views/base/tpl/tool/blockcountry.tpl
>(3)
>    M _protected/framework/Mvc/Controller/Controller.class.php (23)
>    A _protected/framework/Mvc/Model/BlockCountry.class.php (78)
>    A _repository/upgrade/12.1.0-12.6.0/data/sql/MySQL/upgrade.sql (15)
>A _repository/upgrade/12.1.0-12.6.0/data/sql/PostgreSQL/upgrade.sql
>(20)
>    A _repository/upgrade/12.1.0-12.6.0/info/conclusion.php (22)
>    A _repository/upgrade/12.1.0-12.6.0/info/config.ini (7)
>    A _repository/upgrade/12.1.0-12.6.0/info/introduction.php (22)
>    M templates/themes/base/tpl/top_menu.inc.tpl (1)
>
>-- Patch Links --
>
>https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/206.patch
>https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/206.diff
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/206

-- 
Polyna-Maude R.-Summerside

**Comment by pH-7** [comment]
Hey PM, great if that can help :)

The best is always to create a separated branch (and now this one has already been merged ^^).

Since you are a member of the org, you don't even need to use your fork. 
- Just clone it `git clone git@github.com:pH7Software/pH7-Social-Dating-CMS.git`
-  Create a new branch (never push changes on master).
- Push it
- Open a PR

P.S. If you use your fork, please always update the repo first  (git pull), before starting changes to avoid conflicts.

**Comment by polynamaude** [comment]
Good ! You confirm what I believed.

PM

Le 20 mai 2018 16:36:20 EDT, "♚ PH⑦ Soria ♛" <notifications@github.com> a écrit :
>Hey PM, great if that can help :)
>
>The best is always to create a separated branch (and now this one has
>already been merged ^^).
>
>Since you are a member of the org, you don't even need to use your
>fork. 
>- Just clone it `git clone
>git@github.com:pH7Software/pH7-Social-Dating-CMS.git`
>-  Create a new branch (never push changes on master).
>- Push it
>- Open a PR
>
>P.S. If you use your fork, please always update the repo first  (git
>pull), before starting changes to avoid conflicts.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/206#issuecomment-390510516

-- 
Polyna-Maude R.-Summerside

**Comment by pH-7** [comment]
👍 😃

**Comment by polynamaude** [comment]
Hi Ph,
Did the Pull Request and recejved 36 messages about style violation. Find that great to have automatic code validation. I'll give a check at what is said but probably a fotmatting mode that I've set wrong or a CR/LF conversion from Windows.

Cheers !
PM

Le 20 mai 2018 17:08:38 EDT, "♚ PH⑦ Soria ♛" <notifications@github.com> a écrit :
>👍 😃 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pH7Software/pH7-Social-Dating-CMS/pull/206#issuecomment-390512890

-- 
Polyna-Maude R.-Summerside

**Pull request merged**
