### PR TITLE
Add To Home Screen

### PR DESCRIPTION
**Pull request by Undefined-Variables**
This is required to allow user to ATHS

### CODE REVIEW

**Comment by pH-7** [comment]
Good! Have you tested it? How it goes...?

**Comment by Undefined-Variables** [comment]
Yes! Will not work without it! :-)

**Comment by Undefined-Variables** [comment]
Once added all the information is available in development tools!

**Comment by Undefined-Variables** [comment]
Could improved further...

Yours...
yours

yours2


Mine...
mine
mine2

Yours is missing theme_color and apple icon, the theme color is set in the manifest however its "transparent".

**Comment by pH-7** [comment]
> Yes! Doesn't work properly via Chrome without :)

Great! Thanks!

**Comment by pH-7** [comment]
👍

**Comment by pH-7** [comment]
> Could improved further...
> 
> Yours...
> yours
> 
> yours2
> 
> Mine...
> mine
> mine2
> 
> Yours is missing theme_color and apple icon, the theme color is set in the manifest however its "transparent".

Good to know this. Do you mind to set the apple icon in there? FYI, all icons are located in: https://github.com/pH7Software/pH7-Social-Dating-CMS/tree/master/templates/system/modules/pwa/themes/base/img

**Comment by Undefined-Variables** [comment]
Yeah no problem I will do so today!

**Comment by pH-7** [comment]
> Yeah no problem I will do so today!

That's amazing! Thank you!

**Pull request merged**
