### PR TITLE
Update global.js

### PR DESCRIPTION
**Pull request by Undefined-Variables**
Also found the following errors?

showField is defined but never used?
openBox is defined but never used?
oEvent is defined but never used?
loadingImg is defined but never used?

### CODE REVIEW

**Comment by pH-7** [comment]
Thank you @Undefined-Variables! I really appreciate your help. However, the semicolons aren't needed here, and I believe it makes the code harder to read inside of these scopes.. 

Indeed, the functions you mentioned aren't used anymore in the code and can be safely removed from the JS file. Good catch :)

**Comment by Undefined-Variables** [comment]
Hey @pH-7 I understand the semicolons are not needed here or at all in JavaScript but its been drummed in to my head to always use them so caught my eye. I do agree though the code has a neater flow without them... I have a list of these functions that I have to remove. They are throwing errors and causing issues for my security setup. 

No need to thank me just giving a little back for your hard work my friend!

**Comment by pH-7** [comment]
> No need to thank me just giving a little back for your hard work my friend!

Highly appreciate it! 😊

**Comment by pH-7** [comment]
> Hey @pH-7 I understand the semicolons are not needed here or at all in JavaScript but its been drummed in to my head to always use them so caught my eye. I do agree though the code has a neater flow without them... I have a list of these functions that I have to remove. They are throwing errors and causing issues for my security setup.

I understand. I will consider this PR then. It's still odd that your security the missing semicolons are causing issues with your security setups. What kind of settings do you have...?

**Comment by pH-7** [comment]
> Do you want me to pull each time?

What do you mean exactly?

**Comment by Undefined-Variables** [comment]
I use a monitor service called ionCube24, you upload a script they provide to the root directory and add a JavaScript in script tags just after your body tag. You then set any folders that will see changes in them and enable it. If anything changes in the code it is blocked and a notification is sent to you. 

The great thing about this is is shows you any PHP/JS error that crop up and shows you JS errors in a way you would never see otherwise (picture). I have pages of errors mainly from things that have been defined but not used.

Capture
 :)

**Comment by Undefined-Variables** [comment]
> > Do you want me to pull each time?
> 
> What do you mean exactly?

Do you want me to point out each of these functions that are defined but no longer used?

**Pull request closed without merging**
