### PR TITLE
Changed Display (Needed)

### PR DESCRIPTION
**Pull request by Undefined-Variables**
After using this I quickly realized some navigation is needed browser side so changed from "standalone"  to "minimal-ui" which adds a tiny bar to the top of window with refresh, back arrow, minimize, close buttons and options drop down.

### CODE REVIEW

**Comment by Undefined-Variables** [comment]
@PH-7 how do I use the Cors API Class? I have written a script that takes postcodes and uses Google Distance Matrix to return the distance between the two postcodes. On my development server it works  but I am not getting anything on the production server. I understand the basics but how do I include Cors to allow this to work?

    use PH7\Framework\Api\AllowCors ????;

**Comment by polynamaude** [comment]
Not by including a library or object in your namespace that you gonna solve this...

**Comment by Undefined-Variables** [comment]
Agreed I was having a puzzled moment :/ I have remembered the api module and now I understand :)

**Comment by Undefined-Variables** [comment]
@pH-7 I need a bit of help... How can I get the users avatar URL? The path is 

    /public_html/data/system/modules/user/avatar/img/undefined-variables/

But every user has a single char random letter like 

````
1-400.jpg
1-200.jpg
1-150.jpg
1-100.jpg
1-64.jpg
1-32.jpg
1.jpg

````

Which standard sizes a set for each user. But how do I deal with the randomness?

**Comment by Undefined-Variables** [comment]
Database names the 1.jpg so look that up and use regex 

Getting that value solves the puzzle.

**Pull request merged**
